feat: adds support for cross account ecr repositories
concourse/registry-image-resource pull request #253
Opened 2020-10-30 22:21 UTC by cludden

2020-11-02 15:23 UTC, xtremerui commented
@cludden could you give some context of this PR? Thx.

2020-11-02 16:23 UTC, cludden commented
added some additional context in the PR comment

2020-11-02 18:13 UTC, xtremerui commented
Might be an unrelated question, how does the auth work when accessing an image from a ECR that owned by other account since you can only provide one set of credentials?

2020-11-02 19:13 UTC, chenbh commented
This sounds very similar to #252, the main difference being #252 allows for explicit repo url whereas this one infers the repo url from the auth token

@vixus0 would passing in an auth token in order to access a cross-account ecr repo work for you?

2020-11-03 08:58 UTC, vixus0 commented
@chenbh Yeah, if I understand correctly this PR allows me to explicitly specify the AWS account ID to pull the image from - that works!

2020-11-03 11:26 UTC, cludden commented
Good catch! I didn't realize this resource is building the ECR registry using the first result from the `GetAuthorizationToken` output's `AuthorizationData` list. I've updated the PR to accept a single `aws_ecr_registry_id` string parameter, that if specified, overrides the default behavior.

2020-11-03 11:30 UTC, cludden commented
> Might be an unrelated question, how does the auth work when accessing an image from a ECR that owned by other account since you can only provide one set of credentials?
By default, if no registry ids (aws account ids) are specified, the `GetAuthorizationToken` call requests an authorization token for the account to which the requesting credentials belong. This PR modifies the resource to allow the resource to specify an account other than the principal's account id. Additionally, the ECR repository in the other account requires a resource policy granting cross account access. more info here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/security_iam_service-with-iam.html#security_iam_service-with-iam-resource-based-policies

2020-11-03 13:47 UTC, xtremerui commented on types.go
> +	if source.AWSECRRegistryId == "" {
```suggestion
	if source.AWSECRRegistryId != "" {
```

2020-11-03 13:49 UTC, xtremerui requested changes
wondering is it possible to add a test to cover this change?

2020-11-03 18:18 UTC, cludden commented
slight refactor to add some basic tests around the GetAuthorizationTokenInput modification, left the existing `ECR integration is experimental and untested"` warning in place.

2020-11-06 18:13 UTC, cludden commented
bumping for visibility

2020-11-06 21:50 UTC, xtremerui approved these changes

2020-11-06 21:51 UTC, merged